In [1]:
import re
import numpy as np
import pandas as pd
import datetime as dt

# Turn off warnings
import warnings
warnings.filterwarnings('ignore')

import geocoder

with open(r'/home/harrisonized/Desktop/gmaps_apikey.txt') as f: # Grab API Key
    api_key = f.readline()
    f.close

In [2]:
valuecount_190330_df_08to12 = pd.read_csv(r"valuecount_190330_df_08to12.csv") # File import

In [3]:
# Grabbing the latlong data
station_name_index_df = valuecount_190330_df_08to12[['StationName']] # Create new dataframe with station names
station_name_index_df['latlong'] =  station_name_index_df.StationName.apply(lambda x: x+' Station, NY') # Creates a column with lat long as search parameter
station_name_index_df

         StationName                      latlong
0    34 ST-HERALD SQ  34 ST-HERALD SQ Station, NY
1     34 ST-PENN STA   34 ST-PENN STA Station, NY
2     TIMES SQ-42 ST   TIMES SQ-42 ST Station, NY
3      FLUSHING-MAIN    FLUSHING-MAIN Station, NY
4              59 ST            59 ST Station, NY
5    42 ST-PORT AUTH  42 ST-PORT AUTH Station, NY
6     59 ST COLUMBUS   59 ST COLUMBUS Station, NY
7              86 ST            86 ST Station, NY
8    GRD CNTRL-42 ST  GRD CNTRL-42 ST Station, NY
9    JKSN HT-ROOSVLT  JKSN HT-ROOSVLT Station, NY
10       CHAMBERS ST      CHAMBERS ST Station, NY
11            145 ST           145 ST Station, NY
12             23 ST            23 ST Station, NY
13    ATL AV-BARCLAY   ATL AV-BARCLAY Station, NY
14            125 ST           125 ST Station, NY
15             14 ST            14 ST Station, NY
16    47-50 STS ROCK   47-50 STS ROCK Station, NY
17          GRAND ST         GRAND ST Station, NY
18         CHURCH AV        CHURCH AV Station, NY
19        57 ST-7 AV       57 ST-7 AV Station, NY
20   LEXINGTON AV/63  LEXINGTON AV/63 Station, NY
21    QUEENSBORO PLZ   QUEENSBORO PLZ Station, NY
22       NOSTRAND AV      NOSTRAND AV Station, NY
23     JUNCTION BLVD    JUNCTION BLVD Station, NY
24   42 ST-BRYANT PK  42 ST-BRYANT PK Station, NY
25             50 ST            50 ST Station, NY
26    MYRTLE-WYCKOFF   MYRTLE-WYCKOFF Station, NY
27   CROWN HTS-UTICA  CROWN HTS-UTICA Station, NY
28         DEKALB AV        DEKALB AV Station, NY
29   34 ST-HUDSON YD  34 ST-HUDSON YD Station, NY
..               ...                          ...
180  W 8 ST-AQUARIUM  W 8 ST-AQUARIUM Station, NY
181      BEACH 60 ST      BEACH 60 ST Station, NY
182      BUSHWICK AV      BUSHWICK AV Station, NY
183           215 ST           215 ST Station, NY
184      BEACH 25 ST      BEACH 25 ST Station, NY
185       PARK PLACE       PARK PLACE Station, NY
186   HOWARD BCH JFK   HOWARD BCH JFK Station, NY
187           104 ST           104 ST Station, NY
188            55 ST            55 ST Station, NY
189      ATLANTIC AV      ATLANTIC AV Station, NY
190      BEACH 36 ST      BEACH 36 ST Station, NY
191      BEACH 44 ST      BEACH 44 ST Station, NY
192  AQUEDUCT RACETR  AQUEDUCT RACETR Station, NY
193  WORLD TRADE CTR  WORLD TRADE CTR Station, NY
194        NASSAU AV        NASSAU AV Station, NY
195  ASTORIA DITMARS  ASTORIA DITMARS Station, NY
196   COURT SQ-23 ST   COURT SQ-23 ST Station, NY
197            39 AV            39 AV Station, NY
198           121 ST           121 ST Station, NY
199  METROPOLITAN AV  METROPOLITAN AV Station, NY
200         BROADWAY         BROADWAY Station, NY
201    GREENPOINT AV    GREENPOINT AV Station, NY
202            36 AV            36 AV Station, NY
203   WOODHAVEN BLVD   WOODHAVEN BLVD Station, NY
204    CYPRESS HILLS    CYPRESS HILLS Station, NY
205            30 AV            30 AV Station, NY
206    75 ST-ELDERTS    75 ST-ELDERTS Station, NY
207  85 ST-FOREST PK  85 ST-FOREST PK Station, NY
208         AVENUE X         AVENUE X Station, NY
209         AVENUE P         AVENUE P Station, NY

[210 rows x 2 columns]

In [4]:
#Warning: Takes a long time
for i in range(len(station_name_index_df['latlong'])):
    station_name_index_df['latlong'][i] = geocoder.google(station_name_index_df['latlong'][i], key=api_key).latlng
station_name_index_df

         StationName                                  latlong
0    34 ST-HERALD SQ         [40.7488979, -73.98878859999999]
1     34 ST-PENN STA                 [40.751056, -73.9903102]
2     TIMES SQ-42 ST                [40.7545563, -73.9866737]
3      FLUSHING-MAIN         [40.7595582, -73.82992209999999]
4              59 ST                [40.6415685, -74.0176783]
5    42 ST-PORT AUTH         [40.7578346, -73.99146259999999]
6     59 ST COLUMBUS                 [40.7684839, -73.981807]
7              86 ST                [40.7795016, -73.9555724]
8    GRD CNTRL-42 ST         [40.7521647, -73.97715339999999]
9    JKSN HT-ROOSVLT                 [40.746739, -73.8909986]
10       CHAMBERS ST                [40.7155134, -74.0092227]
11            145 ST                [40.8240532, -73.9447623]
12             23 ST                [40.7413626, -73.9891335]
13    ATL AV-BARCLAY         [40.6837598, -73.97875739999999]
14            125 ST                [40.8043863, -73.9374292]
15             14 ST         [40.73747540000001, -73.9970975]
16    47-50 STS ROCK           [40.75885, -73.98118610000002]
17          GRAND ST                [40.7182003, -73.9935756]
18         CHURCH AV                [40.6495233, -73.9632839]
19        57 ST-7 AV                 [40.765564, -73.9803309]
20   LEXINGTON AV/63          [40.764629, -73.96611299999999]
21    QUEENSBORO PLZ                [40.7505127, -73.9398439]
22       NOSTRAND AV         [40.6697362, -73.95050890000002]
23     JUNCTION BLVD                 [40.749203, -73.8693365]
24   42 ST-BRYANT PK                [40.7548368, -73.9841215]
25             50 ST         [40.7620363, -73.98632909999999]
26    MYRTLE-WYCKOFF                 [40.699686, -73.9117713]
27   CROWN HTS-UTICA         [40.6689469, -73.93183379999999]
28         DEKALB AV         [40.68982020000001, -73.9811611]
29   34 ST-HUDSON YD                [40.7549713, -74.0010084]
..               ...                                      ...
180  W 8 ST-AQUARIUM  [40.57612779999999, -73.97596539999999]
181      BEACH 60 ST           [40.59244, -73.78928300000001]
182      BUSHWICK AV         [40.7002958, -73.94116439999999]
183           215 ST                [40.8695946, -73.9153019]
184      BEACH 25 ST         [40.59946790000001, -73.7618536]
185       PARK PLACE                [40.7132422, -74.0092559]
186   HOWARD BCH JFK          [40.660476, -73.83030099999999]
187           104 ST                [40.6951456, -73.8443046]
188            55 ST                [40.6315514, -73.9956328]
189      ATLANTIC AV                 [40.675554, -73.9030576]
190      BEACH 36 ST                 [40.595532, -73.7681238]
191      BEACH 44 ST         [40.5929209, -73.77594839999999]
192  AQUEDUCT RACETR                [40.6721498, -73.8356843]
193  WORLD TRADE CTR         [40.7126452, -74.00989799999999]
194        NASSAU AV                [40.7238944, -73.9506777]
195  ASTORIA DITMARS                  [40.7750119, -73.91211]
196   COURT SQ-23 ST         [40.7480508, -73.94704779999999]
197            39 AV                [40.7526897, -73.9328056]
198           121 ST                [40.7006094, -73.8281286]
199  METROPOLITAN AV                 [40.7121327, -73.889276]
200         BROADWAY                [40.7623472, -73.9256595]
201    GREENPOINT AV                [40.7301618, -73.9540458]
202            36 AV                 [40.7668516, -73.921313]
203   WOODHAVEN BLVD         [40.6939097, -73.85139269999999]
204    CYPRESS HILLS  [40.68994860000001, -73.87257310000001]
205            30 AV                 [40.7668516, -73.921313]
206    75 ST-ELDERTS         [40.69143649999999, -73.8665512]
207  85 ST-FOREST PK                [40.6924861, -73.8590708]
208         AVENUE X                [40.5896822, -73.9742509]
209         AVENUE P                [40.6087814, -73.9729084]

[210 rows x 2 columns]

In [5]:
station_name_index_df.to_csv("latlong.csv") # Export output to CSV file for easy access

In [9]:
latlong_df = pd.read_csv(r"latlong.csv")

In [11]:
# Formatting Stuff
latlong_df = latlong_df.drop(columns="Unnamed: 0")
latlong_df.latlong = latlong_df.latlong.apply(lambda x : re.sub("\[", "", x)).apply(lambda x : re.sub("\]", "", x)).apply(lambda x : re.sub(",", "", x)) # Remove brackets and commas
latlong_df = latlong_df.join(latlong_df.latlong.str.split(' ', expand = True)) # Split coordinate values into two columns
latlong_df = latlong_df.drop(columns = ["latlong"]).rename(columns={0: "Latitude", 1: "Longitude"}) # Deleting and renaming columns
latlong_df.Longitude = latlong_df.Longitude.apply(lambda x : float(x)) # Converting to float
latlong_df.Latitude = latlong_df.Latitude.apply(lambda x : float(x)) # Converting to float
latlong_df

         StationName   Latitude  Longitude
0    34 ST-HERALD SQ  40.748898 -73.988789
1     34 ST-PENN STA  40.751056 -73.990310
2     TIMES SQ-42 ST  40.754556 -73.986674
3      FLUSHING-MAIN  40.759558 -73.829922
4              59 ST  40.641568 -74.017678
5    42 ST-PORT AUTH  40.757835 -73.991463
6     59 ST COLUMBUS  40.768484 -73.981807
7              86 ST  40.779502 -73.955572
8    GRD CNTRL-42 ST  40.752165 -73.977153
9    JKSN HT-ROOSVLT  40.746739 -73.890999
10       CHAMBERS ST  40.715513 -74.009223
11            145 ST  40.824053 -73.944762
12             23 ST  40.741363 -73.989133
13    ATL AV-BARCLAY  40.683760 -73.978757
14            125 ST  40.804386 -73.937429
15             14 ST  40.737475 -73.997097
16    47-50 STS ROCK  40.758850 -73.981186
17          GRAND ST  40.718200 -73.993576
18         CHURCH AV  40.649523 -73.963284
19        57 ST-7 AV  40.765564 -73.980331
20   LEXINGTON AV/63  40.764629 -73.966113
21    QUEENSBORO PLZ  40.750513 -73.939844
22       NOSTRAND AV  40.669736 -73.950509
23     JUNCTION BLVD  40.749203 -73.869337
24   42 ST-BRYANT PK  40.754837 -73.984122
25             50 ST  40.762036 -73.986329
26    MYRTLE-WYCKOFF  40.699686 -73.911771
27   CROWN HTS-UTICA  40.668947 -73.931834
28         DEKALB AV  40.689820 -73.981161
29   34 ST-HUDSON YD  40.754971 -74.001008
..               ...        ...        ...
180  W 8 ST-AQUARIUM  40.576128 -73.975965
181      BEACH 60 ST  40.592440 -73.789283
182      BUSHWICK AV  40.700296 -73.941164
183           215 ST  40.869595 -73.915302
184      BEACH 25 ST  40.599468 -73.761854
185       PARK PLACE  40.713242 -74.009256
186   HOWARD BCH JFK  40.660476 -73.830301
187           104 ST  40.695146 -73.844305
188            55 ST  40.631551 -73.995633
189      ATLANTIC AV  40.675554 -73.903058
190      BEACH 36 ST  40.595532 -73.768124
191      BEACH 44 ST  40.592921 -73.775948
192  AQUEDUCT RACETR  40.672150 -73.835684
193  WORLD TRADE CTR  40.712645 -74.009898
194        NASSAU AV  40.723894 -73.950678
195  ASTORIA DITMARS  40.775012 -73.912110
196   COURT SQ-23 ST  40.748051 -73.947048
197            39 AV  40.752690 -73.932806
198           121 ST  40.700609 -73.828129
199  METROPOLITAN AV  40.712133 -73.889276
200         BROADWAY  40.762347 -73.925659
201    GREENPOINT AV  40.730162 -73.954046
202            36 AV  40.766852 -73.921313
203   WOODHAVEN BLVD  40.693910 -73.851393
204    CYPRESS HILLS  40.689949 -73.872573
205            30 AV  40.766852 -73.921313
206    75 ST-ELDERTS  40.691436 -73.866551
207  85 ST-FOREST PK  40.692486 -73.859071
208         AVENUE X  40.589682 -73.974251
209         AVENUE P  40.608781 -73.972908

[210 rows x 3 columns]

In [8]:
# Export output to CSV file for easy access

latlong_df.to_csv("latlong_clean.csv") # Pipe this back into the main project branch